### ISSUE TITLE
How to get ping

### ISSUE THREAD

**Issue by tomocrafter** [benediktschmitt/py-ts3#47]
Hi developers. How can i get user ping? i googled but i couldnt find how to.

**Comment by benediktschmitt** [comment]
Hi,

you can use the ``serverinfo`` command to get the *VIRTUALSERVER_TOTAL_PING* value. I don't know how to get the ping for each client (perhaps ``clientinfo``).

You can read more about the query commands here: http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

**Comment by tomocrafter** [comment]
OK! thx for given infomation

**Comment by tomocrafter** [comment]
hmm
i cant get cline ping from `clientinfo`
i want client ping....

I will try again!

**Comment by tomocrafter** [comment]
Samehow It seems we can get users ping from 
```
serverrequestconnectioninfo
```


but its cant get each users ping
.....!?!?

**Comment by benediktschmitt** [comment]
I took a quick look into the query manual and did not find such a command. Since this library is only a python wrapper for the telnet based TS3 query api, you should give the official ts3 forum http://forum.teamspeak.com/ a try. 
If there's a command which gives you the client ping, then you can use it in *py-ts3*. Otherwise you can't.

**Comment by benediktschmitt** [comment]
I'm closing this issue because it is not related to the *py-ts3* API itself, but the official TS3 Server Query protocol.
