### ISSUE TITLE
Correct way to use threading?

### ISSUE THREAD

**Issue by LickABrick** [benediktschmitt/py-ts3#76]
What is the correct way to use threading? Whenever I create a thread which for example sends a message it will work the first 1-3 times but after that it won't work anymore.

Example thread:

```
def test_def():
    while True:
        time.sleep(5)
        msg = "Test Message!"
        ts3conn.sendtextmessage(targetmode="2", target=1, msg=msg)

thread = Thread(target=test_def, daemon=True)
thread.start()
```

This thread is initiated before the bot has connected, but will wait 5 seconds before sending its first message.

**Comment by AdorablePotato** [comment]
Sorry for the late reply.
All TS3 objects are not thread safe, so the easiest way to avoid errors is to allow only one thread read/write access to a ts3 connection.
Your specific example does not work (at least if there's not some other code), because you use a daemon thread. The interpreter does not wait for daemon threads and so the thread is canceled when the interpreter finishes.

**Comment by whookie** [comment]
You can use a little workaround for thread-safety.
Like, if you pass a (I believe mutable) object to a function, it gets passed by reference.
That way you can make a custom mutable queue structure in the main thread and just spawn a bunch of non-blocking threads pushing actions into the queue, and have the main thread execute the queue.

If that is what you mean by thread-safe...

I actually have used that for a command handler, all user commands get pushed into a queue and handled when there is time. (Kinda like fake-asynchonous programming)
